Add controllers
nix-pix/java-shareit pull request #1
Opened 2023-04-14 21:51 UTC by nix-pix

Проект ShareIt. Техническое задание. Часть 1

2023-04-15 12:46 UTC, db-exp requested changes

2023-04-15 12:46 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (itemDto.getName() == null || itemDto.getName().isBlank() || itemDto.getDescription() == null || itemDto.getDescription().isBlank()) {
кмк лучше перенести аннотациями на dto

2023-04-15 12:46 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                          @RequestBody ItemDto itemDto,
тут тоже можно Valid

2023-04-15 12:46 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemDto.java
> +public class ItemDto {
давай добавим аннотация про Blank итп сюда, чтобы не проверять руками в контроллере

2023-04-15 12:46 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    private ItemRequest request;
1) таких запросов может быть много
2) лучше вынести как отдельный класс

2023-04-15 12:46 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        if (userDto.getEmail() == null || userDto.getName() == null) {
тут тоже достаточно аннотаций на классе так как Valid
Если хочется кинуть кастомную ошибку, можно так 
https://stackoverflow.com/questions/62896233/how-to-throw-custom-exception-in-proper-way-when-using-javax-validation-valid

2023-04-16 11:25 UTC, nix-pix commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (itemDto.getName() == null || itemDto.getName().isBlank() || itemDto.getDescription() == null || itemDto.getDescription().isBlank()) {
Да, так проще и меньше кода, поправил.

2023-04-16 11:25 UTC, nix-pix commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                          @RequestBody ItemDto itemDto,
Спасибо, добавил

2023-04-16 11:27 UTC, nix-pix commented on src/main/java/ru/practicum/shareit/item/ItemDto.java
> +public class ItemDto {
добавил

2023-04-16 12:11 UTC, nix-pix commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        if (userDto.getEmail() == null || userDto.getName() == null) {
Ок, поправил

2023-04-16 12:16 UTC, nix-pix commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    private ItemRequest request;
Не понял, что имеется ввиду

2023-04-16 20:00 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                          @RequestBody ItemDto itemDto,
Не понял, что ломается - напиши, пожалуйста, ошибку к следующему спринту

2023-04-16 20:03 UTC, db-exp approved these changes

2023-04-16 20:03 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemDto.java
> +public class ItemDto {
https://www.baeldung.com/java-bean-validation-not-null-empty-blank 
NotBlank уже может в NotNull, можно не дублировать

2023-04-16 20:28 UTC, nix-pix commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                          @RequestBody ItemDto itemDto,
Если добавить @Valid к ItemDto, то тесты не проходят. Сразу выдается ошибка по 40 тестам postman

2023-04-16 20:34 UTC, merged